name: Tests
on:
  push:
    branches: [dev]

jobs:

  run-tests:
    name: Run Test
    runs-on: ubuntu-latest
    env:
      DB_NAME: test
      DB_USER: dev1
      DB_PASS: pass1
    steps:
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Setup PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_NAME }}"
          sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH ENCRYPTED PASSWORD '${{ env.DB_PASS }}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DB_NAME }} TO ${{ env.DB_USER }}"          

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run Unit + Integration Tests
        run: 'mvn clean install'

  merge-to-main:
    name: Merge dev branch to main
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: fregante/setup-git-user@v1
      - name: Merge
        run: |
          git checkout main
          git merge dev --commit -m 'merge dev -> main'
          git push origin main